name: Test

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11', 'macos-12', 'macos-13', 'ubuntu-20.04', 'ubuntu-22.04', 'windows-2022']
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run all
      - uses: ./
